import Head from "next/head";
import Header from "../components/Header";
import Banner from "../components/Banner";
import EnjoyCrypto from "../components/EnjoyCrypto";
import BuyAndSell from "../components/BuyAndSell";
import MultiCrypto from "../components/MultiCrypto";
import ReadyToStart from "../components/ReadyToStart";
import Footer from "../components/Footer";
import { symbols } from "../constants/coins";
import getCoins from "../apis/getCoins";
import CryptoMarket from "../components/CryptoMarket";

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>DCX.DO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./assets/icons/logo.svg" />
      </Head>
      <Header />
      <Banner {...props} />
      <EnjoyCrypto />
      <BuyAndSell />
      <CryptoMarket />
      <MultiCrypto />
      <ReadyToStart />
      <Footer />
    </div>
  );
}

{
  /* <Orbit borderColor="red" spin="left">
          <Nucleus backgroundColor="red" size={20} />
          <Planet size={10} spin="left" />
        </Orbit>
        <Orbit animationSpeedInSeconds={2} borderColor="#95abd5" spin="right">
          <Planet backgroundColor="blue" size={10} />
          <Planet backgroundColor="green" shouldSpin={false} size={20} />
        </Orbit> */
}

export const getServerSideProps = async () => {
  const coins = await getCoins();
  return { props: { coins } };
};
